#!/usr/bin/env python3
"""
Agent Skill: Create Plan
Generates structured action plans for processing tasks
"""

import json
import sys
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, Any

from base_skill import BaseSkill, run_skill


class CreatePlanSkill(BaseSkill):
    """Skill to create structured action plans"""

    def _execute_impl(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Create a plan for the given task"""
        task_description = params.get('task_description', '')
        files_to_process = params.get('files_to_process', [])
        priority = params.get('priority', 'medium')

        # Generate plan ID
        plan_id = f"PLAN_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        # Create plan content
        plan_content = self._generate_plan_content(
            plan_id,
            task_description,
            files_to_process,
            priority
        )

        # Write plan file
        plan_path = self.vault_path / 'Plans' / f"{plan_id}.md"
        self.write_file(plan_path, plan_content)

        self.logger.info(f"Created plan: {plan_path.name}")

        return {
            "plan_id": plan_id,
            "plan_path": str(plan_path),
            "task_description": task_description,
            "priority": priority
        }

    def _generate_plan_content(self, plan_id: str, task_description: str,
                             files_to_process: list, priority: str) -> str:
        """Generate the plan content based on task type"""

        # Determine task type from description
        task_type = self._determine_task_type(task_description)

        # Generate steps based on task type
        steps = self._generate_steps(task_type, files_to_process)

        # Calculate estimated time
        estimated_time = self._estimate_time(task_type, len(files_to_process))

        # Generate plan content
        content = f"""---
id: {plan_id}
created: {datetime.now().isoformat()}
priority: {priority}
task_type: {task_type}
status: pending
estimated_duration: {estimated_time} minutes
---

# Action Plan: {task_description}

## Overview
**Task**: {task_description}
**Priority**: {priority.upper()}
**Created**: {datetime.now().strftime('%Y-%m-%d %H:%M')}
**Estimated Duration**: {estimated_time} minutes

## Files to Process
"""

        # Add files section
        if files_to_process:
            content += "\n".join(f"- {Path(f).name}" for f in files_to_process)
        else:
            content += "- No specific files (general task)"

        content += f"""

## Steps to Complete
"""

        # Add steps
        for i, step in enumerate(steps, 1):
            content += f"{i}. {step}\n"

        content += f"""

## Completion Criteria
- [ ] All steps completed
- [ ] Files moved to appropriate locations
- [ ] Dashboard updated
- [ ] Logs updated

## Notes
"""

        # Add task-specific notes
        if task_type == 'file_processing':
            content += """
- Ensure proper file locking during processing
- Verify file integrity after operations
- Check for any approval requirements
"""
        elif task_type == 'approval_workflow':
            content += """
- Human approval required before execution
- Document approval decision and timestamp
- Move to appropriate folder after decision
"""
        elif task_type == 'system_maintenance':
            content += """
- Perform backup before making changes
- Test in development mode first
- Document any configuration changes
"""

        content += f"""

## Next Steps
After completion:
1. Update this plan with actual completion time
2. Add any lessons learned
3. Archive plan to Done folder

---
*Plan generated by AI Employee - Bronze Tier*
"""

        return content

    def _determine_task_type(self, task_description: str) -> str:
        """Determine the type of task from description"""
        desc_lower = task_description.lower()

        if any(word in desc_lower for word in ['file', 'process', 'document']):
            return 'file_processing'
        elif any(word in desc_lower for word in ['approve', 'approval', 'authorize']):
            return 'approval_workflow'
        elif any(word in desc_lower for word in ['maintenance', 'update', 'configure']):
            return 'system_maintenance'
        elif any(word in desc_lower for word in ['email', 'message', 'communication']):
            return 'communication'
        else:
            return 'general'

    def _generate_steps(self, task_type: str, files_to_process: list) -> list:
        """Generate appropriate steps based on task type"""
        base_steps = [
            "Review task requirements and files",
            "Check Company Handbook for relevant rules"
        ]

        if task_type == 'file_processing':
            file_count = len(files_to_process)
            return base_steps + [
                f"Process {file_count} file(s) according to type",
                "Extract metadata and determine required actions",
                "Create approval requests if needed",
                "Execute processing actions",
                "Move processed files to Done folder"
            ]
        elif task_type == 'approval_workflow':
            return base_steps + [
                "Review approval request details",
                "Verify authorization requirements",
                "Document approval decision",
                "Execute approved actions or notify rejection",
                "Update audit log"
            ]
        elif task_type == 'system_maintenance':
            return base_steps + [
                "Backup current configuration",
                "Execute maintenance tasks",
                "Verify system functionality",
                "Update documentation",
                "Notify stakeholders of completion"
            ]
        elif task_type == 'communication':
            return base_steps + [
                "Review communication content",
                "Check recipient and authorization",
                "Prepare message with proper formatting",
                "Queue for sending or create approval request",
                "Log communication attempt"
            ]
        else:
            return base_steps + [
                "Analyze task requirements",
                "Determine optimal approach",
                "Execute required actions",
                "Verify completion",
                "Document results"
            ]

    def _estimate_time(self, task_type: str, file_count: int) -> int:
        """Estimate time required for task in minutes"""
        base_time = {
            'file_processing': 5,
            'approval_workflow': 10,
            'system_maintenance': 15,
            'communication': 3,
            'general': 5
        }

        time_per_file = {
            'file_processing': 2,
            'approval_workflow': 0,
            'system_maintenance': 0,
            'communication': 1,
            'general': 1
        }

        base = base_time.get(task_type, 5)
        per_file = time_per_file.get(task_type, 1)

        return base + (per_file * file_count)


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python create_plan.py '<json_params>'")
        sys.exit(1)

    run_skill(CreatePlanSkill, sys.argv[1])